name: Aggregate Release Notes

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version to aggregate'
        required: true
        type: string
      repos:
        description: 'Comma-separated list of repositories'
        required: true
        default: 'foo,bar,baz'
      output_path:
        description: 'Output path for release notes'
        required: false
        default: 'releases'

jobs:
  aggregate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Install Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
      
      - name: Cache Cargo
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      
      - name: Build Release Aggregator
        run: cargo build --release
      
      - name: Generate Release Notes
        run: |
          ./target/release/release-aggregator generate \
            --version "${{ inputs.version }}" \
            --repos "${{ inputs.repos }}" \
            --org "${{ github.repository_owner }}" \
            --output "${{ inputs.output_path }}/${{ inputs.version }}.md" \
            --categorize \
            --include-prs \
            --include-issues
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RUST_LOG: info
      
      - name: Commit Release Notes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add "${{ inputs.output_path }}/"
          git commit -m "📝 Add release notes for v${{ inputs.version }}" || echo "No changes to commit"
          git push